spring.application.name=ecommerce

server.port=8080

#DB ecommerce
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# --- CREDENCIALES DE CLOUDINARY ---
cloudinary.cloud_name=doq0aezh4
cloudinary.api_key=796726252379242
cloudinary.api_secret=f3cQDSD3W-tAXx6CxbygGqI4EGE

# Límite de tamaño para un solo archivo (ejemplo: 10 MegaBytes)
spring.servlet.multipart.max-file-size=10MB

# Límite de tamaño para toda la petición junta (ejemplo: 50 MegaBytes)
spring.servlet.multipart.max-request-size=50MB

# --- TU SECRETO DE JWT (El que quitamos de JwtUtil) ---
jwt.secret=TU_NUEVO_SECRETO_LARGO_Y_SEGURO_AQUI

# CONFIGURACIÓN DE CORREO
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alextejada025@gmail.com
spring.mail.password=jktzomkjqhewsxbf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true